trigger:
  branches:
    include:
      - master

variables:
  azureSubscription: 'AzureConnection-Project2'
  webAppName: 'azure-keyvault-app'
  resourceGroupName: 'Project2'
  nodeVersion: '18.x'

pool:
  name: Default  # Using self-hosted agent (e.g., your MacBook)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion)'
      runtimeStack: 'NODE|18-lts'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      if [ -f package.json ] && grep -q '"build":' package.json; then
        echo "Build script found. Running..."
        npm run build
      else
        echo "No build script found. Skipping build step."
      fi
    displayName: 'Optional Build Step'

  # ✅ Archive the app including node_modules and all source files
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
      replaceExistingArchive: true
      includePatterns: |
        **/*
        !node_modules/**  # Exclude node_modules
    displayName: 'Archive Files (Including node_modules)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
      ArtifactName: 'drop'
    displayName: 'Publish Artifact'

  # ✅ Download artifact for deployment step
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(Pipeline.Workspace)'
    displayName: 'Download Published Artifact'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: 'webApp'
      appName: '$(webAppName)'
      package: '$(Pipeline.Workspace)/drop/$(webAppName).zip'
    displayName: 'Deploy to Azure Web App'
