trigger:
  branches:
    include:
      - master  # ✅ Changed from 'main' to 'master'

variables:
  azureSubscription: 'AzureConnection-Project2'
  webAppName: 'azure-keyvault-app'
  resourceGroupName: 'Project2'
  nodeVersion: '18.x'

pool:
  name: Default  # ✅ Use self-hosted agent on your MacBook

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion)'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npm run build || echo "no build step"
    displayName: 'Build App'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
      replaceExistingArchive: true
    displayName: 'Archive Files'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
      ArtifactName: 'drop'
    displayName: 'Publish Artifact'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: 'webApp'
      appName: '$(webAppName)'
      package: '$(Pipeline.Workspace)/drop/$(webAppName).zip'
    displayName: 'Deploy to Azure Web App'
