trigger:
  branches:
    include:
      - master

variables:
  azureSubscription: 'AzureConnection-Project2'
  webAppName: 'azure-keyvault-app'
  resourceGroupName: 'Project2'
  nodeVersion: '18.x'

pool:
  name: Default  # Using self-hosted agent (e.g., your MacBook)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    npm install --production
    npm list --depth=0
  displayName: 'Install production dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
    includePatterns: |
      **/*
      !node_modules/**  # Exclude node_modules from zip
  displayName: 'Create deployment package'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    runtimeStack: 'NODE|18-lts'
    appSettings: |
      [
        {
          "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
          "value": "true"
        },
        {
          "name": "WEBSITE_NODE_DEFAULT_VERSION",
          "value": "18-lts"
        },
        {
          "name": "KEY_VAULT_NAME",
          "value": "project2KeyVault321"
        }
      ]