trigger:
  branches:
    include:
      - master

variables:
  azureSubscription: 'AzureConnection-Project2'
  webAppName: 'azure-keyvault-app'
  resourceGroupName: 'Project2'
  nodeVersion: '18.x'

pool:
  name: Default  # Using self-hosted agent (MacBook)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Use Node.js $(nodeVersion)'

- script: npm ci
  displayName: 'Install dependencies (clean install)'

- script: npm run build || echo "No build script found, skipping"
  displayName: 'Run build (if any)'

- script: npm prune --production
  displayName: 'Prune devDependencies'

- task: ArchiveFiles@2
  displayName: 'Package application'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
    includePatterns: |
      **/*
      !**/*.log
      !**/node_modules/**
      !**/.env
      !**/tests/**
      !**/__tests__/**

- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    runtimeStack: 'NODE|18-lts'
    appSettings: |
      -KEY_VAULT_NAME project2KeyVault321
      -SCM_DO_BUILD_DURING_DEPLOYMENT=true
      -WEBSITE_NODE_DEFAULT_VERSION=18-lts
      -NODE_ENV=production
